### ISSUE TITLE
'iosfwd' file not found

### ISSUE THREAD

**Issue by rubensantiago** [facebook/Sonar#28]
After importing `<Sonar/SonarClient.h>`, 'iosfwd' cannot be found in `json.h`. This is a mixed Obj-C & Swift project.

**Comment by priteshrnandgaonkar** [comment]
We do not support swift projects yet. We are working on it. Look at the issue #13

**Comment by JiandanDream** [comment]
The same, but mine is a Objc project.

**Comment by iineva** [comment]
Xcode Version 9.4.1 (9F2000)
Create a new Objective-C project, same issue.

**Comment by noahsark769** [comment]
@JiandanDream @iineva I'm seeing this error also. AFAIK, this should work since Cocoapods should be able to compile this objc module to make it usable in a Swift module. Do either of you have a sample project I could look at to try to reproduce? An objc project fails with this error would be best for investigation purposes.

**Comment by iineva** [comment]
@noahsark769 You can try this: [Test.zip](https://github.com/facebook/Sonar/files/2126230/Test.zip)

```shell
pod update
pod install
# than build project.
```

**Comment by noahsark769** [comment]
Can confirm that the same error happens for me on @iineva 's test project, which has no Swift (I'm running Xcode Version 9.3 (9E145)). @priteshrnandgaonkar can we reopen this since it's not a Swift specific issue?

**Comment by noahsark769** [comment]
@iineva after trying a few things, I was able to make your project compile by adding the search path `"${PODS_ROOT}/SonarKit"` with recursive = true to "Search Paths" under "Build Settings".

![image](https://user-images.githubusercontent.com/1168853/41760612-303c9f72-75a9-11e8-986e-6e510fe658a0.png)

I have to say that I'm not exactly sure what's happening here to fix it, but I tested it twice. Unfortunately, with my project, I still get the same error :(

**Comment by noahsark769** [comment]
It looks like https://github.com/facebook/yoga/issues/697, https://github.com/facebook/react-native/issues/17556, https://github.com/facebook/yoga/issues/711 were similar issues that React Native had with Swift projects.

The [fix](https://github.com/facebook/react-native/pull/18492) there seems to have been to specify `public_header_files` in [Yoga's podspec](https://github.com/facebook/yoga/blob/master/Yoga.podspec) specifically so that headers with c++ are excluded. My guess is we'll need to some something similar for Sonar/SonarKit.

**Comment by noahsark769** [comment]
This ended up being a search path issue. See explanation at #13
