### ISSUE TITLE
Unable to build Android Project

### ISSUE THREAD

**Issue by rohfosho** [facebook/Sonar#37]
Can't build the android project because the `fb` directory is not present.

This causes the following files to not be found:

`fb/visibility.h`
`fb/fbjni.h`
`fb/**`

**Comment by wickedev** [comment]
also following files are not found
`fb/assert.h`
`fb/fbjni/ByteBuffer.h`
`fb/log.h`
`fb/Countable.h`
`fb/visibility.h`
`fb/fbjni/CoreClasses.h`

**Comment by andreiverdes** [comment]
Also the `https://github.com/mozilla/rhino` lib is missing and `Console` plugin is throwing errors

**Comment by kele86838437** [comment]
Fatal error: '__config' file not found when folly built

**Comment by priteshrnandgaonkar** [comment]
Currently on master branch, project builds through gradle.But at runtime the sample app freezes. The issue is with `sonarfb.so` file. We are investigating the bug and any help in regards to this will be appreciated. 

Run `./gradlew :sample:installDebug` from the root directory. Make sure the emulator is up before running the previous command.

**Comment by priteshrnandgaonkar** [comment]
On current master, one can build and run sonar and sample android app. Gradle builds are working,
try `./gradlew :sample:installDebug`. Closing the issue as it is fixed.
