### ISSUE TITLE
Add iOS physical device support

### ISSUE THREAD

**Issue by qokelate** [facebook/Sonar#76]
**Sonar.app** iOS not found, any help?

my code: 
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
   ......
       SonarClient *client = [SonarClient sharedClient];
    SKDescriptorMapper *mapper = [[SKDescriptorMapper alloc] initWithDefaults];
    [client addPlugin:[[SonarKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:mapper]];
    [client start];
   ......
}

```

**Comment by ranchen516** [comment]
+1

**Comment by qokelate** [comment]
It works on simulator! How to setup on my phone?

**Comment by jknoxville** [comment]
At the moment, for iOS, sonar only supports physical devices.
There's a note on this page but we should probably make it more prominent: https://fbsonar.com/docs/getting-started.html

The reason is that on android, we can use adb to write sonar's CA certificate to the app's internal data directory over usb. This certificate then gets pinned in the app so it can trust sonar.
But on iOS, there is no such mechanism to do this, so we'll have to devise an alternate method of securely deploying the desktop's sonar certificate to the mobile app, and/or introduce an optional opt-out config setting for desktop-app verification.
